### ISSUE TITLE
Support large scripts

### ISSUE THREAD

**Issue by AsynchronousAI** [argon-rbx/argon#17] opened 2024-01-04 01:43 UTC
I have a large game, each file is like 2k lines, I want to switch to an VSCode system but I cannot use Argon because it gives me a "Number of requests exceeded limit".

**Comment by DervexHero** [comment] 2024-01-04 17:03
`Number of requests exceeded limit` error is not related in any way to the size of your scripts. In fact your place exceeded Roblox http limit which is **500 requests per minute**. It's likely becuase you are using another plugin that sends http requests. Could you check that first?

**Comment by AsynchronousAI** [comment] 2024-01-04 23:33
Nope, I only have Argon as a plugin with permission to use HTTPS. And this error occurs on a new open of Roblox Studio, I have tried restarting.

**Comment by DervexHero** [comment] 2024-01-06 10:43
Okay, that's weird. How many instances in your project in total do you have then?

**Comment by AsynchronousAI** [comment] 2024-01-07 15:41
~20

**Comment by DervexHero** [comment] 2024-01-07 21:11
Well so that is actually a bug, I'm not gonna bother fixing the legacy version since I'm very close to finishing Argon 2 and in fact I'm going to start working on the new Roblox plugin following week.

**Comment by AsynchronousAI** [comment] 2024-01-07 22:11
> Well so that is actually a bug, I'm not gonna bother fixing the legacy version since I'm very close to finishing Argon 2 and in fact I'm going to start working on the new Roblox plugin following week.

Good luck on Argon 2, but even so today my team was practicing for the game jam and argon began flooding with the Number of requests exceeded limit even when there was just 1 script with 1 line.

**Comment by DervexHero** [comment] 2024-01-07 22:22
That's too bad. Just did quick test and take a look:

https://github.com/argon-rbx/argon/assets/78505208/b59d2faf-4ffa-4b40-9505-49886738afba

I was able to sync over 6k loc script with no problems. So could you give me some more details because as you can see I can't reproduce your problem.

**Comment by AsynchronousAI** [comment] 2024-01-07 23:42
Very odd, the same issue occured on my Macbook and my Mac that I am using right now. 

Ill give it a try in Rojo and see if it is Argon related or just a general problem

**Comment by AsynchronousAI** [comment] 2024-01-07 23:48
Rojo has the same error

**Comment by DervexHero** [comment] 2024-01-08 11:57
Okay, so I'm closing the issue as it's not Argon related.

As I said before it looks like you have something in your place that exceeds Roblox's 500 http requests per minute limit.

**Closed by DervexHero** 2024-01-08 11:57 UTC
